### ISSUE TITLE
GetDamagingWeapon is nil

### ISSUE THREAD

**Issue by sertacdncl** [mythicrp/mythic_hospital#12]
`local weapon = GetDamagingWeapon(ped) `

```
function GetDamagingWeapon(ped)
    for k, v in pairs(Config.Weapons) do
        if HasPedBeenDamagedByWeapon(ped, k, 1) then
            ClearEntityLastDamageEntity(ped)
            return v
        end
    end

    return nil
end
```

Its turning nil value and the code is not working with  

#8

**Comment by Alzar** [comment]
Info on what weapon you're being damaged by would be great, and what version of the script your using. As I have not had any issues and cannot reproduce it outside of removing weapons from the list and being injured by it.

**Comment by sertacdncl** [comment]
I tried every weapon and every weapon is getting nil. I am using latest essentialmode and es extended. I am using your script latest version

**Comment by Alzar** [comment]
Tried for a few hours using every gun in the game, and couldn't reproduce it. Outside of anymore information (And of course assuming you're using standalone and not the ESX fork) or repro steps there's really nothing more I can do. Suggest downloading a clean version and trying again, as I've not had anyone else have issues with this
