### ISSUE TITLE
3d text on damaged bones

### ISSUE THREAD

**Issue by J4far** [mythicrp/mythic_hospital#13]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
- when a player gets injured, a police or an ems can check the damaged bones. it can show as 3d text on the location of that bone.

- ems can heal specific bone damage.

![Capdfdfture](https://user-images.githubusercontent.com/56239323/67640421-928a3b80-f90b-11e9-9705-4a17c61cbe47.PNG)

**Comment by Alzar** [comment]
I have no plans to introduce dependencies outside of what is already there, especially not any sort of framework stuff. Any script that is wanting to add this functionality can do so relatively easily as there is a server export which allows a script to get a players injuries.
