### ISSUE TITLE
After Get Revived respawan After xxx minutes text not going  !!!

### ISSUE THREAD

**Issue by subhampro** [mythicrp/mythic_hospital#14]
**Describe the bug**
After Get Revived respawan After xxx minutes text not going  !!!
After Get Revived respawan After xxx minutes text not going  !!!
**To Reproduce**
1. Go to '...' CHECK IN POSITION
2. Click on '....' E
3. Scroll down to '....' N/A
4. See error - REVIVEING THEN AFTER REVIVE  Still Showing Respawan Available after xxx minutes
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/33375250/68953082-2ce0ef00-07e7-11ea-863a-da2ace8680a7.png)

**FiveM Artifacts Version:**
Artifacts Version Your Server Is Running
Leatest
**Additional context**
Please reply !

**Comment by Alzar** [comment]
That isn't mythic hospital, you either need to integrate the resource adding that to it, or remove it.

**Comment by subhampro** [comment]
I am using esx_ambulancejob and mythic_hospital ... So at old ver of esx there is a Client Side .Lua file called main.lua where I add this code :--`TriggerEvent('esx_ambulancejob:revive')` 
The Client/main.lua looks like ---:
`RegisterNetEvent('mythic_hospital:client:FinishServices')
AddEventHandler('mythic_hospital:client:FinishServices', function()
	local player = PlayerPedId()
	
	if IsPedDeadOrDying(player) then
		local playerPos = GetEntityCoords(player, true)
		NetworkResurrectLocalPlayer(playerPos, true, true, false)
	end
	
	SetEntityHealth(player, GetEntityMaxHealth(player))
    ClearPedBloodDamage(player)
    SetPlayerSprint(PlayerId(), true)
    TriggerEvent('mythic_hospital:client:RemoveBleed')
    TriggerEvent('mythic_hospital:client:ResetLimbs')
    TriggerEvent('esx_ambulancejob:revive')
    exports['mythic_notify']:SendAlert('inform', 'You\'ve been treated and billed.')
    LeaveBed()
end)`
to  fix this problem. But new ver there is no client/main.lua please help me with that .
