### ISSUE TITLE
Please Intrigate Esx_ambulancejob with mythic_hospital !

### ISSUE THREAD

**Issue by subhampro** [mythicrp/mythic_hospital#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

So when we use esx_ambulancejob and mythic hospital at same time after revive it's not revive you completely timer shows after revive which comes from esx_ambulancejob .

**Describe alternatives you've considered**

**Additional context**

**Comment by Alzar** [comment]
No, will not be adding ESX or any framework depedency on it. Anyone is more than welcome to fork it and make any edits they desire to it.

**Comment by subhampro** [comment]
atleast u can help me to say where i need to put this code ! 
` if IsPedDeadOrDying(PlayerPedId()) then TriggerEvent('esx_ambulancejob:revive') end` as i mentioned there is no clint side  main.lua file
