### ISSUE TITLE
No Notification

### ISSUE THREAD

**Issue by yagizher** [mythicrp/mythic_hospital#16]
I cant get any notifications, i tried everything, i have everything updated, this is the start line:

start mythic_notify
start mythic_progbar
start mythic_hospital

i tried to change start with ensure but there is still no notification at all, can you help me please? asap.Thanks.

**Comment by Alzar** [comment]
Are you using standalone or ESX fork?

**Comment by yagizher** [comment]
Standalone

**Comment by Alzar** [comment]
OK, need to know what errors are occuring or else there is literally nothing I can help you with. "No notification" isn't helpful at all

**Comment by yagizher** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/52376710/69056547-47061180-0a21-11ea-91ef-bb06cadcad1c.png)
![Screenshot_2](https://user-images.githubusercontent.com/52376710/69056548-47061180-0a21-11ea-8443-bac5bf75ea5d.png)
There is no error.

**Comment by Alzar** [comment]
Are you actually sure you're getting injured? Turn on debugging and see if the damage events are firing

**Comment by yagizher** [comment]
My fault.Fixed but when there is a notification its not dissapearing its always staying in my screen.

**Comment by Alzar** [comment]
Correct, it's using persistent alerts and will remain on screen until player dies or injuries are treated.
