### ISSUE TITLE
A little help if possible please.

### ISSUE THREAD

**Issue by PixelWorldRP** [mythicrp/mythic_hospital#4]
Hello, We're looking into Implementing this into our Framework, and are at the stage of syncing via the database, however on your FiveM post you state to run the

`mythic_hospital:client:SyncLimbs`

function however i can not see this defined anywhere within the script? Could you tell me what it is to Sync the damage, I'm assuming this will allow to reSync the damage upon a player reconnecting if they have not had it treated?

At present, its correctly saving in my Database and Reading the data in the database,

**Comment by Alzar** [comment]
Interesting, must have accidently removed that converting to release version. Woops!

`
RegisterNetEvent('mythic_hospital:client:SyncLimbs')
AddEventHandler('mythic_hospital:client:SyncLimbs', function(limbs)
    BodyParts = limbs
    DoLimbAlert()
end)
`

Is the function for syncing limbs, SyncBleed is there and what you can call to sync bleed from server-side.

**Comment by PixelWorldRP** [comment]
No problem, this event handler you have posted, does this go in any of the client files? or in main.lua or wound.lua?

Thanks for the quick response :-)

**Comment by Alzar** [comment]
wound.lua client file

**Comment by PixelWorldRP** [comment]
Thank you.
