### ISSUE TITLE
Documentation on how to adjust settings

### ISSUE THREAD

**Issue by Ex0r** [mythicrp/mythic_hospital#7]
**Is your feature request related to a problem? Please describe.**
Injuries happen far too easily and often. Players tripping over curbs or falling from even a short height cause major injury and bleeding. Even falling off a car or running into a stsionary vehicle causes damage. 

It's very hard to RP when players are continually having to go to pillbox to be treated. Most time is spent in there. 

**Describe the solution you'd like**
A way to adjust damage percentage so that the chance of damage isnt so high.

**Comment by Alzar** [comment]
Made some changes that add some RNG to apply damage, with some thresholds to force damage. These are on the 2.0 dev branch, which I'm going to hope to get done and merged to master tonight

**Comment by Ex0r** [comment]
Has this made it to a stable state yet? Been waiting for it to get pushed to master so we can test it out.

**Comment by Alzar** [comment]
Been in a stable state for a few weeks, merged to master as nothing of major issue was ever brought up and I've not found anything.

Config files are all documented about what they do.
