### ISSUE TITLE
There isn't any notification.

### ISSUE THREAD

**Issue by sertacdncl** [mythicrp/mythic_hospital#8]
I activated the script. But there is no error and there is no notification when bleeding. I don't understand why. I tried version 2.0 and esx version but there is no notif and error.

**Comment by danishrp** [comment]
Dependencies :

Mythic Notify
Mythic Progress Bar
Pillbox Interior

**Comment by sertacdncl** [comment]
I have all of that.

**Comment by Alzar** [comment]
Never had issues with it, and with no errors going alongside this nothing I can do to help you.

Make sure you have an updated Mythic Notify as function calls have since changed.

**Comment by sertacdncl** [comment]
I downloaded all scripts again and i test it. Nothing :(


https://gyazo.com/5256bf3df5f9ff047ba98153a04be2af

**Comment by sertacdncl** [comment]
I tried to print isBleeding value. Is always 0

**Comment by sertacdncl** [comment]
And i also tried so much prints and 

local weapon = GetDamagingWeapon(ped)

is nil and the code block is not working
https://gyazo.com/110a21ba1ab3419a4af864dc595f9b4e

**Comment by sertacdncl** [comment]
I deleted weapon ~= nil check and notify is working but why weapon is nil i don't understand
